Hello!
thiagoyeds/hello-hacktoberfest-2022 pull request #14
Opened 2022-10-20 10:54 UTC by HarshAggarwal1

2022-10-20 10:55 UTC, HarshAggarwal1 commented
Hello message done.

2022-10-20 11:15 UTC, HarshAggarwal1 commented
Added javascript folder. Please accept this request

2022-10-20 11:48 UTC, HarshAggarwal1 commented
added html dir.

2022-10-21 10:44 UTC, thiagoyeds requested changes

2022-10-21 10:44 UTC, thiagoyeds commented on java/hello-HarshAggarwal1.java
>  }
Don't remove `java/hello-thiagoyeds.java`, in case there will be 2 files in java directory: `hello-thiagoyeds.java` and `java/hello-HarshAggarwal1.java`.
Create a new file named `java/hello-HarshAggarwal1.java` and put that content inside it.

2022-10-21 10:44 UTC, thiagoyeds commented on hello-thiagoyeds.cpp
> +}
This file should be in c++ folder, maybe your branch is out of date, do a `git rebase origin/main` to pull the changes and update that location file. It's not allowed to mess with files that don't have your {Github username}

2022-10-21 12:44 UTC, HarshAggarwal1 commented
Hi, I have updated the repository and made the changes you suggested. I am sorry for the mess created; please check the modifications; if I still have an error, please let me know. Thanks.

2022-10-22 20:05 UTC, HarshAggarwal1 commented
Hi, may you please review the changes? If anything is still wrong, then please let me know.

2022-10-23 15:46 UTC, thiagoyeds requested changes
move `pyhton/hello-thiagoyeds.py` to `python/hello-thiagoyeds.py`
the correct dir is `python` instead of ``pyhton`

2022-10-23 15:46 UTC, thiagoyeds commented on java/hello-thiagoyeds.java
> +        System.out.println("Hello Hacktoberfest 2021! My name is thiagoyeds!");
Please, apply the suggestion

```suggestion
        System.out.println("Hello Hacktoberfest 2022! My name is thiagoyeds!"); 
```

2022-10-23 16:15 UTC, HarshAggarwal1 commented on java/hello-thiagoyeds.java
> +        System.out.println("Hello Hacktoberfest 2021! My name is thiagoyeds!");
done

2022-10-23 16:16 UTC, HarshAggarwal1 commented
done changes

2022-10-24 12:32 UTC, thiagoyeds approved these changes

2022-10-24 12:34 UTC, merged